### ISSUE TITLE
Not creating log archives

### ISSUE THREAD

**Issue by krasi-georgiev** [michaloo/logrotate#1]
Hi
Does this rotate time based or just when the logs reach the 500mb limit ?

I have run  it few days ago , but can't see any archives anywhere in the host .

**Comment by michaloo** [comment]
Hello,
the default settings - logrotate configuration template `logrotate.tmpl` and default environmental variables set in `Dockerfile` - should rotate logs every 3 days or when the log size exceeds 512mb.
Where do you search for a container logs?

**Comment by krasi-georgiev** [comment]
I will check in few days again as I had to recreate all containers yesterday,

I searched in /var/logs and /var/lib/docker/containers/.....

**Comment by krasi-georgiev** [comment]
I can now confirm that after 6 days it hasn't rotate any of the files.

here is part of the log
http://pastebin.com/5LyjhFjQ

**Comment by michaloo** [comment]
As stated in #2 PR logrotate `size` directive disables time based rotating. The PR fixes the issue changing default configuration template to be time based (thanks @vipconsult). I will introduce small enhancement to make it working either way depending on the container env variables.
